# Generated by Django 3.2.12 on 2022-03-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthenticationApp', '0002_auto_20220314_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
